name: Ecosounds
url: http://research.ecosounds.org
main_url: https://www.ecosounds.org
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: pygments
safe: true
lsi: false
timezone: Australia/Brisbane
defaults:
  scope:
    path: ""
    types: posts
  values:
    permalink: pretty
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock, vendor]
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
