name: Ecosounds
url: http://research.ecosounds.org
main_url: https://www.ecosounds.org
markdown: redcarpet
redcarpet:
  extensions: 
    - tables
    - smart
    - autolink
    - strikethrough
    - superscript
    - space_after_headers
    - with_toc_data
    - fenced_code_blocks
    - no_intra_emphasis
    - footnotes
    - highlight
highlighter: pygments
safe: true
lsi: false
timezone: Australia/Brisbane
defaults:
  scope:
    path: ""
    types: posts
  values:
    permalink: pretty
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock, vendor]
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
