name: Ecosounds
url: http://www.ecosounds.org
markdown: redcarpet
highlighter: pygments
safe: true
lsi: false
timezone: Australia/Brisbane
defaults:
  scope:
    path: ""
    types: posts
  values:
    permalink: pretty
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock, vendor]
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
