name: QUT Ecoacoustics
url: https://research.ecosounds.org
main_url: https://www.ecosounds.org
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
safe: false
lsi: false
timezone: Australia/Brisbane
defaults:
  scope:
    path: ""
    types: posts
  values:
    permalink: pretty
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock, vendor]
include: [ "_redirects" ]
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
